name: Package release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.ARTIFACT_REGISTRY_GCP_CREDENTIALS }}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish artifacts
        run: |
          pip install --upgrade twine keyrings.google-artifactregistry-auth requests PyOpenSSL cryptography ndg-httpsclient
          python -m twine upload --skip-existing --verbose --repository-url https://northamerica-northeast1-python.pkg.dev/earnest-math-277914/ecofusion-py/ dist/*
